filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
    json.keys_under_root: true
    json.add_error_key: true
    ignore_older: 72h

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

setup.template.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log
  name: filebeat
  keepfiles: 7
  permissions: 0644
