version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    platform: linux/amd64
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: filebeat
    platform: linux/amd64
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/var/log:ro
    depends_on:
      - elasticsearch
    command: ["--strict.perms=false"]

  auditbeat:
    image: docker.elastic.co/beats/auditbeat:7.10.2
    container_name: auditbeat
    platform: linux/amd64
    user: root
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_READ
    volumes:
      - ./auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml:ro
    depends_on:
      - elasticsearch
    command: ["--strict.perms=false"]

  fake-logger:
    image: busybox
    container_name: fake-logger
    volumes:
      - ./logs:/logs
    command: /bin/sh -c "while true; do echo '{\"@timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"event\":\"Simulated brute force\"}' >> /logs/test.log; sleep 10; done"

volumes:
  elasticsearch-data:
